"""Generated agent context.

`AGENT_CONTEXT.md` is the bounded import surface consumed by an agent CLI's
native project-context mechanism. It overlays approved project notes on global notes;
candidates and drafts never enter it.
"""
from __future__ import annotations

import sqlite3
from datetime import datetime, timezone
from pathlib import Path

MAX_NOTES = 10
MAX_CHARS = 4000

HEADER = (
    "<!-- Generated by above-all from approved global and project notes. "
    "Do not edit by hand; regenerate with `above-all note context`. -->\n"
)


def merged_active_notes(global_db, project_db, backend, limit=MAX_NOTES):
    global_notes = backend.active_notes(global_db, limit)
    project_notes = backend.active_notes(project_db, limit) if project_db else []
    merged = {note["id"]: dict(note, scope="global") for note in global_notes}
    merged.update({note["id"]: dict(note, scope="project") for note in project_notes})
    return list(merged.values())[:limit]


def generate_agent_context(scope_dir: Path, db: sqlite3.Connection, backend, global_db: sqlite3.Connection | None = None) -> Path:
    scope_dir.mkdir(parents=True, exist_ok=True)
    notes = merged_active_notes(global_db or db, db if global_db else None, backend)
    parts = [HEADER, "# Project context\n"]
    used = 0
    for note in notes:
        body = note["body"].strip()
        if body.startswith("# "):  # body already carries its H1; drop the duplicate
            body = body.split("\n", 1)[1].strip() if "\n" in body else ""
        block = f"## {note['title']}\n\n_Source: {note['scope']} knowledge_\n\n{body}\n"
        if used + len(block) > MAX_CHARS:
            break
        parts.append(block)
        used += len(block)
    parts.append(f"\n_Generated {datetime.now(timezone.utc).isoformat()} from {len(notes)} notes._\n")
    path = scope_dir / "AGENT_CONTEXT.md"
    path.write_text("\n".join(parts), encoding="utf-8")
    return path
